site_name: WYF的个人网站
site_url: https://ryan1702.github.io/first-website/
site_author: WYF
site_description: WYF的个人网站

nav:
  - 首页: index.md
  - 个人介绍: about.md
  - 课内学习:
    - 学习计划: in-school/plan.md
  - 课外学习:
    - 算法竞赛:
      - 学习计划: out-school/algorithms/plan.md
      - 算法大全:
        - 高精度:
          - 高精度加法: out-school/algorithms/算法大全/高精度/加法.md
          - 高精度减法: out-school/algorithms/算法大全/高精度/减法.md
          - 高精度乘法: out-school/algorithms/算法大全/高精度/乘法.md
          - 高精度除法（高精度除以低精度）: out-school/algorithms/算法大全/高精度/除法1.md
          - 高精度除法（高精度除以高精度）: out-school/algorithms/算法大全/高精度/除法2.md
        - 排序算法:
          - 冒泡排序: out-school/algorithms/算法大全/排序/冒泡排序.md
          - 选择排序: out-school/algorithms/算法大全/排序/选择排序.md
          - 插入排序: out-school/algorithms/算法大全/排序/插入排序.md
          - 归并排序: out-school/algorithms/算法大全/排序/归并排序.md
          - 快速排序: out-school/algorithms/算法大全/排序/快速排序.md
          - 基数排序: out-school/algorithms/算法大全/排序/基数排序.md
          - 堆排序: out-school/algorithms/算法大全/排序/堆排序.md
        - 二分:
          - 二分答案: out-school/algorithms/算法大全/二分/二分答案.md
        - 搜索:
          - 记忆化搜索: out-school/algorithms/算法大全/搜索/记忆化搜索.md
        - DP:
          - 背包问题:
            - 01背包: out-school/algorithms/算法大全/DP/背包/01背包.md
            - 01背包k优解: out-school/algorithms/算法大全/DP/背包/01背包k优解.md
            - 01背包方案以及方案数: out-school/algorithms/算法大全/DP/背包/01背包方案以及方案数.md
            - 01背包最优方案数: out-school/algorithms/算法大全/DP/背包/01背包最优方案数.md
            - 完全背包: out-school/algorithms/算法大全/DP/背包/完全背包.md
            - 多重背包: out-school/algorithms/算法大全/DP/背包/多重背包.md
            - 多重背包单调队列优化: out-school/algorithms/算法大全/DP/背包/多重背包单调队列优化.md
          - 其他:
            - 区间DP: out-school/algorithms/算法大全/DP/区间DP.md
            - 最长不下降子序列: out-school/algorithms/算法大全/DP/最长不下降子序列.md
        - 字符串:
          - 字符串哈希: out-school/algorithms/算法大全/字符串/字符串哈希.md
          - KMP: out-school/algorithms/算法大全/字符串/KMP.md
          - 扩展KMP: out-school/algorithms/算法大全/字符串/扩展KMP.md
          - 马拉车算法: out-school/algorithms/算法大全/字符串/马拉车算法.md
          - Trie: out-school/algorithms/算法大全/字符串/Trie.md
          - Trie最大异或对: out-school/algorithms/算法大全/字符串/Trie最大异或对.md
          - AC自动机: out-school/algorithms/算法大全/字符串/AC自动机.md
      - 题解:
        - 企鹅: out-school/algorithms/题解/企鹅.md
        - 取石子: out-school/algorithms/题解/取石子.md
        - 老虎机: out-school/algorithms/题解/老虎机.md

theme:
  name: material
  language: zh
  palette:
    # 日间模式
    - scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-night
        name: 切换至夜间模式
    # 夜间模式
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs      # 使用 Tab 分类
    - navigation.top       # 返回顶部按钮
    - navigation.indexes   # 点击 Tab 可直接打开说明页
    - search.suggest       # 搜索补全
    - search.highlight     # 搜索高亮
    - content.code.copy    # 代码一键复制
    - content.action.edit  # 编辑源文件按钮
  icon:
    repo: fontawesome/brands/github

edit_uri: edit/main/docs/
repo_url: https://github.com/ryan1702/first-website/
repo_name: first-website
copyright: 吴悠凡 CC-BY-4.0

extra:
  social:
    - name: GitHub | Ryan1702
      icon: fontawesome/brands/github
      link: https://github.com/Ryan1702

plugins:
  - search:
      lang: [zh, en]
  - tags

markdown_extensions:
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums: true
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.betterem
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.emoji

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - javascripts/katex-init.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css